### ISSUE TITLE
historicApi.query.staking.slashingSpans is not a function on /accounts/*/staking-info

### ISSUE THREAD

**Issue by jkbrsn** [paritytech/substrate-api-sidecar#1822]
**Description**

Met with a code 500 error when attempting to get staking info for an account on Polkadot AssetHub:

```
curl  https://api-asset-hub-polkadot-sidecar.n.dwellir.com/<api key>/accounts/<account>/staking-info
{
  "code": 500,
  "message": "historicApi.query.staking.slashingSpans is not a function",
  "stack": "TypeError: historicApi.query.staking.slashingSpans is not a function\n    at AccountsStakingInfoService.fetchStakingData (/usr/lib/node_modules/@substrate/api-sidecar/build/src/services/accounts/AccountsStakingInfoService.js:287:39)\n    at AccountsStakingInfoService.fetchAccountStakingInfo (/usr/lib/node_modules/@substrate/api-sidecar/build/src/services/accounts/AccountsStakingInfoService.js:189:90)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async AccountsStakingInfoController.getAccountStakingInfo (/usr/lib/node_modules/@substrate/api-sidecar/build/src/controllers/accounts/AccountsStakingInfoController.js:129:30)\n    at async /usr/lib/node_modules/@substrate/api-sidecar/build/src/controllers/AbstractController.js:313:9",
  "level": "error"
}
```

**Steps to Reproduce**

* `polkadot-parachain v1.20.1` with `--pruning=archive`
* `substrate-api-sidecar v20.11.0`
* Run `/accounts/*/staking-info`

Unknown: if there is something particular to the addresses we targeted, but I do not think so.

**Expected vs. Actual Behavior**

Not expecting an error.

**Comment by TarikGul** [comment]
Yea let me check this out, we fixed this specifically a while ago as part of our integration, and a quick look over the code when connected to asset hub we removed the slashingSpan call and set it to 0. I'll try and reproduce.

**Comment by TarikGul** [comment]
So i wasn't able to reproduce this with any block post migration:

```
2025-11-05 19:57:56 info: Version: 20.11.0
2025-11-05 19:57:56 info: Initializing APIs
2025-11-05 19:57:56 info: Initializing API for wss://rpc-asset-hub-polkadot.luckyfriday.io
2025-11-05 19:57:56 warn: API/INIT: RPC methods not decorated: archive_v1_body, archive_v1_call, archive_v1_finalizedHeight, archive_v1_genesisHash, archive_v1_hashByHeight, archive_v1_header, archive_v1_stopStorage, archive_v1_storage, archive_v1_storageDiff, archive_v1_storageDiff_stopStorageDiff, chainHead_v1_body, chainHead_v1_call, chainHead_v1_continue, chainHead_v1_follow, chainHead_v1_header, chainHead_v1_stopOperation, chainHead_v1_storage, chainHead_v1_unfollow, chainHead_v1_unpin, chainSpec_v1_chainName, chainSpec_v1_genesisHash, chainSpec_v1_properties, transactionWatch_v1_submitAndWatch, transactionWatch_v1_unwatch, transaction_v1_broadcast, transaction_v1_stop
2025-11-05 19:57:56 info: API initialized for wss://rpc-asset-hub-polkadot.luckyfriday.io with specName statemint
2025-11-05 19:57:56 info: Connected to chain Polkadot Asset Hub on the statemint client at wss://rpc-asset-hub-polkadot.luckyfriday.io
2025-11-05 19:57:56 info: All APIs initialized
2025-11-05 19:57:56 info: Listening on http://127.0.0.1:8080/
2025-11-05 19:57:56 info: Check the root endpoint (http://127.0.0.1:8080/) to see the available endpoints for the current node
2025-11-05 19:58:38 http: GET /accounts/13ougYD2SRkn88L14XiYCJc3mL7AzWoAMVdn1FwLumV49LjU/staking-info 200 5322ms
2025-11-05 19:59:20 http: GET /accounts/13ougYD2SRkn88L14XiYCJc3mL7AzWoAMVdn1FwLumV49LjU/staking-info?at=10259209 200 4967ms
2025-11-05 20:07:56 http: GET /accounts/13ougYD2SRkn88L14XiYCJc3mL7AzWoAMVdn1FwLumV49LjU/staking-info?at=10259207 200 4877ms
2025-11-05 20:08:21 http: GET /accounts/13ougYD2SRkn88L14XiYCJc3mL7AzWoAMVdn1FwLumV49LjU/staking-info?at=10259207 200 92ms
```

**Comment by jkbrsn** [comment]
Thanks for helping out @TarikGul 

After a restart of the API client this morning (UTC+1), the `/accounts/*/staking-info` endpoint now works. No other changes made. We still don't know the original cause but as we've managed to resolve the issue, I'll close this ticket.
