### ISSUE TITLE
yarn does not compile in fresh empty dir

### ISSUE THREAD

**Issue by gww-parity** [paritytech/substrate-api-sidecar#601]
**Description**

does not compile

**Steps to Reproduce**

```
$ mkdir new_empty_dir && cd new_empty_dir
$ yarn add $substrate/api-sidecar
```

**Expected vs. Actual Behavior**

Actual result:

```
$ mkdir new_empty_dir && cd new_empty_dir
$ yarn add $substrate/api-sidecar

yarn add v1.22.10
info No lockfile found.
[1/4] Resolving packages...
warning @substrate/api-sidecar > confmgr > @types/yaml@1.9.7: This is a stub types definition. yaml provides its own type definitions, so you do not need this installed.
[2/4] Fetching packages...
error @edgeware/node-types@3.5.1-erup-4: The engine "node" is incompatible with this module. Expected version "^14.0.0". Got "16.4.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by TarikGul** [comment]
Thanks for bringing up this issue. For now the naive solution would be to change the node version to `14`. I use `nvm` so that would be `nvm use 14.0.0`. In the meantime I will put together a fix for this and try to get it out along with Sidecar [8.0.2 release](https://github.com/paritytech/substrate-api-sidecar/pull/599).

**Comment by TarikGul** [comment]
This issue seems to be with `@edgeware/node-types` via `@polkadot/apps-config` [here](https://github.com/hicommonwealth/edgeware-node-types/blob/master/package.json#L11). The Syntax is wrong and should rather be denoted as `>=14.0.0`

**Comment by TarikGul** [comment]
This should get resolved with sidecar v8.0.3.

**Comment by gww-parity** [comment]
I am js/yarn newbe. Could you provide how can I check it?
I've tried with : `yarn upgrade && yarn add @substrate/api-sidecar` and still the same output.

**Comment by TarikGul** [comment]
Looks like there was a little mistake on my part. Im setting up 8.0.4 right now. I added `@polkadot/apps-config@0.94.2-49` to fix a third party types bundle issue (ended up being two different type bundle problems), but it didnt contain the necessary PR sent to `@edgeware`. The proper version of of apps-config should be `@polkadot/apps-config@0.94.2-72`. Sorry for the delay. You arent doing anything wrong, this will be out today.

**Comment by TarikGul** [comment]
Okay cool, so we just released v8.0.4 and I am not able to reproduce the issue anymore and for node v16.4.2 I am getting the correct behavior when the package is installed. 

To run it you can do the following - 

```
npm install -g @substrate/api-sidecar
export SAS_SUBSTRATE_WS_URL=wss://rpc.polkadot.io
substrate-api-sidecar
```

or if you are using yarn 1.22

```
yarn add global @substrate/api-sidecar
export SAS_SUBSTRATE_WS_URL=wss://rpc.polkadot.io
substrate-api-sidecar
```

Before closing I will make sure it is working for you as well.

**Comment by TarikGul** [comment]
Accidently closed, so I reopened the issue. 

Before closing I will make sure it is working for you as well.

**Comment by gww-parity** [comment]
Finally ! 

Now result is "Done" ! 🚀
